---
BS1:
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['wood']

BS2:
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['wood']

BS3:
  troop_slot: 3
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['food']

BS4:
  troop_slot: 2
  wall_repair: False
  super_mine_gathering: False
  resource_type: ['food', 'wood']
...
